slogo_team12: ColorFeature Class Reference
ColorFeature Class Reference
Public Member Functions
ColorPicker changePenColor (PenHandler penHandler)
ColorPicker changeBGColor (GraphicsContext gc, int displayWidth, int displayHeight)
Public Member Functions inherited from Feature.Feature
Button makeButton (String label, EventHandler< ActionEvent > event)
Package Attributes
final ColorPicker penColorPicker = new ColorPicker()
final ColorPicker BGColorPicker = new ColorPicker()
Detailed Description
Implements ColorPicker to let the user choose pen color and background color.
Author
Yoonhyung Choi
Definition at line 14 of file ColorFeature.java.
Member Function Documentation
ColorPicker ColorFeature.changeBGColor (GraphicsContext gc, int displayWidth, int displayHeight)
Changes background color of the canvas.
Parameters
gc GraphicsContext for the background canvas
displayWidth Canvas Width
displayHeight Canvas Height
Returns
Colorpicker for the background
Definition at line 40 of file ColorFeature.java.
References BGColorPicker.
Referenced by Workspace.addFeatureButtons().
ColorPicker ColorFeature.changePenColor (PenHandler penHandler)
Changes pen color.
Parameters
penHandler PenHandler that controls the pen
Returns
Colorpicker for the pen
Definition at line 23 of file ColorFeature.java.
References penColorPicker, and MovementAndImageAPI.src.PenHandler.setPenColor().
Referenced by Workspace.addFeatureButtons().
Member Data Documentation
final ColorPicker ColorFeature.BGColorPicker = new ColorPicker() package
Definition at line 16 of file ColorFeature.java.
Referenced by changeBGColor().
final ColorPicker ColorFeature.penColorPicker = new ColorPicker() package
Definition at line 15 of file ColorFeature.java.
Referenced by changePenColor().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/ColorFeature.java