slogo_team12: commands.ActivityCommand Class Reference
commands.ActivityCommand Class Reference
Classes
enum CommandType
Public Member Functions
ActivityCommand (GeneralTurtleHandler turtleHandler, CommandType command)
void execute ()
Public Member Functions inherited from commands.CommandsTurtle
CommandsTurtle (GeneralTurtleHandler turtleHandler)
Private Attributes
CommandType myCommand
Additional Inherited Members
Protected Member Functions inherited from commands.CommandsTurtle
GeneralTurtleHandler turtleHandler ()
Package Attributes inherited from commands.CommandsTurtle
GeneralTurtleHandler turtleHandler = null
Detailed Description
executes commands related to turtle activities
Author
Davis, Keng
Definition at line 12 of file ActivityCommand.java.
Constructor & Destructor Documentation
commands.ActivityCommand.ActivityCommand (GeneralTurtleHandler turtleHandler, CommandType command)
Definition at line 17 of file ActivityCommand.java.
Member Function Documentation
void commands.ActivityCommand.execute ()
Implements commands.ICommand.
Definition at line 23 of file ActivityCommand.java.
References MovementAndImageAPI.src.GeneralTurtleHandler.setPenPosition(), MovementAndImageAPI.src.GeneralTurtleHandler.showTurtle(), and commands.CommandsTurtle.turtleHandler().
Member Data Documentation
CommandType commands.ActivityCommand.myCommand private
Definition at line 14 of file ActivityCommand.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/commands/ActivityCommand.java