slogo_team12: Main Class Reference
Main Class Reference
Public Member Functions
void start (Stage primaryStage)
void addKeyboardControl (TabPane tabPane)
Static Public Member Functions
static void main (String[] args)
Private Attributes
Scene myScene
TurtleHandler myActiveTurtle
Map< String, Workspace > workspaceMap
Static Private Attributes
static final int NUMBER_OF_WORKSPACES = 3
static final int BACK_INCREMENT = -10
static final int FORWARD_INCREMENT = 10
static final int RIGHT_ROTATION = 45
static final int LEFT_ROTATION = -45
static final int SCREEN_WIDTH = 1000
static final int SCREEN_HEIGHT = 700
Detailed Description
The main entry point for Slogo. Creates the Scene and adds Slogo workspaces.
Author
Yoonhyung Choi
Definition at line 22 of file Main.java.
Member Function Documentation
void Main.addKeyboardControl (TabPane tabPane)
Adds keyboard control for the turtles.
Parameters
tabPane TabPane where the tabs for the workspaces are located.
Definition at line 78 of file Main.java.
References MovementAndImageAPI.src.TurtleHandler.updateTurtleLocation(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleOrientation().
Referenced by start().
static void Main.main (String[] args) static
the main entry point for the program.
Parameters
args
Definition at line 105 of file Main.java.
void Main.start (Stage primaryStage)
the JavaFX thread entry point. Creates the Stage and scene.
Definition at line 38 of file Main.java.
References addKeyboardControl(), Workspace.createWorkspace(), Workspace.getTurtleHandler(), and NUMBER_OF_WORKSPACES.
Member Data Documentation
final int Main.BACK_INCREMENT = -10 static private
Definition at line 24 of file Main.java.
final int Main.FORWARD_INCREMENT = 10 static private
Definition at line 25 of file Main.java.
final int Main.LEFT_ROTATION = -45 static private
Definition at line 27 of file Main.java.
TurtleHandler Main.myActiveTurtle private
Definition at line 31 of file Main.java.
Scene Main.myScene private
Definition at line 30 of file Main.java.
final int Main.NUMBER_OF_WORKSPACES = 3 static private
Definition at line 23 of file Main.java.
Referenced by start().
final int Main.RIGHT_ROTATION = 45 static private
Definition at line 26 of file Main.java.
final int Main.SCREEN_HEIGHT = 700 static private
Definition at line 29 of file Main.java.
final int Main.SCREEN_WIDTH = 1000 static private
Definition at line 28 of file Main.java.
Map<String,Workspace> Main.workspaceMap private
Definition at line 32 of file Main.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/Main.java