slogo_team12: TurtleDataFeature Class Reference
TurtleDataFeature Class Reference
Public Member Functions
void openTurtleDataPage (Button button, TurtleHandler myTurtleHandler)
void showStage (TurtleHandler myTurtleHandler)
Public Member Functions inherited from Feature.Feature
Button makeButton (String label, EventHandler< ActionEvent > event)
Static Private Attributes
static final int PAGE_HEIGHT = 300
static final int PAGE_WIDTH = 300
Detailed Description
Allows the user to access the turtle information (x position, y position, rotation)
Author
Yoonhyung Choi
Definition at line 15 of file TurtleDataFeature.java.
Member Function Documentation
void TurtleDataFeature.openTurtleDataPage (Button button, TurtleHandler myTurtleHandler)
Opens the turtle data page when the button is clicked.
Parameters
button Associated button
myTurtleHandler TurtleHandler that controls the turtle
Definition at line 24 of file TurtleDataFeature.java.
References showStage().
Referenced by Workspace.addFeatureButtons().
void TurtleDataFeature.showStage (TurtleHandler myTurtleHandler)
Displays the turtle data
Parameters
myTurtleHandler TurtleHandler that controls the turtle
Definition at line 37 of file TurtleDataFeature.java.
References MovementAndImageAPI.src.TurtleHandler.getOrientation(), and MovementAndImageAPI.src.TurtleHandler.getTurtleLocation().
Referenced by openTurtleDataPage().
Member Data Documentation
final int TurtleDataFeature.PAGE_HEIGHT = 300 static private
Definition at line 16 of file TurtleDataFeature.java.
final int TurtleDataFeature.PAGE_WIDTH = 300 static private
Definition at line 17 of file TurtleDataFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/TurtleDataFeature.java