slogo_team12: RefGridFeature Class Reference
RefGridFeature Class Reference
Public Member Functions
void showReferenceGrid (Button button, Pane pane, int displayWidth, int displayHeight)
void drawRefGrid (Pane pane, int displayWidth, int displayHeight)
void removeRefGrid ()
Public Member Functions inherited from Feature.Feature
Button makeButton (String label, EventHandler< ActionEvent > event)
Package Attributes
boolean gridOn = true
Private Attributes
ArrayList< Line > lineList
Static Private Attributes
static final double REFERENCE_LINE_OPACITY = 0.1
static final int REFERENCE_LINE_GAP = 10
Detailed Description
Allows user to toggle on/off a "reference" grid in the display window.
Author
Yoonhyung Choi
Definition at line 14 of file RefGridFeature.java.
Member Function Documentation
void RefGridFeature.drawRefGrid (Pane pane, int displayWidth, int displayHeight)
Draws the reference grid lines onto the display
Parameters
pane Pane where the display is located
displayWidth Display width
displayHeight Display height
Definition at line 48 of file RefGridFeature.java.
References REFERENCE_LINE_GAP.
Referenced by showReferenceGrid().
void RefGridFeature.removeRefGrid ()
Definition at line 61 of file RefGridFeature.java.
Referenced by showReferenceGrid().
void RefGridFeature.showReferenceGrid (Button button, Pane pane, int displayWidth, int displayHeight)
Shows/hides reference grid on the display with a mouse click.
Parameters
button Associated button
pane Pane where the display is located
displayWidth Display width
displayHeight Display height
Definition at line 28 of file RefGridFeature.java.
References drawRefGrid(), and removeRefGrid().
Referenced by Workspace.addFeatureButtons().
Member Data Documentation
boolean RefGridFeature.gridOn = true package
Definition at line 19 of file RefGridFeature.java.
ArrayList<Line> RefGridFeature.lineList private
Definition at line 18 of file RefGridFeature.java.
final int RefGridFeature.REFERENCE_LINE_GAP = 10 static private
Definition at line 17 of file RefGridFeature.java.
Referenced by drawRefGrid().
final double RefGridFeature.REFERENCE_LINE_OPACITY = 0.1 static private
Definition at line 16 of file RefGridFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/RefGridFeature.java