slogo_team12: MovementAndImageAPI.src.PenHandler Class Reference
MovementAndImageAPI.src.PenHandler Class Reference
Public Member Functions
void setPenColor (Color newPenColor)
void setPenPosition (int penPosition)
Color getPenColor ()
int getPenPosition ()
void setLineWidth (double width)
double getLineWidth ()
Private Attributes
Pen mainPen = new Pen()
Detailed Description
Author
Eirika Sawh This class receives commands from the backend about whether or not to update the Pen
Definition at line 10 of file PenHandler.java.
Member Function Documentation
double MovementAndImageAPI.src.PenHandler.getLineWidth ()
Returns
the width of the pen in pixels
Definition at line 58 of file PenHandler.java.
References MovementAndImageAPI.src.Pen.getLineWidth().
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine().
Color MovementAndImageAPI.src.PenHandler.getPenColor ()
Returns
the Pen's color
Definition at line 34 of file PenHandler.java.
References MovementAndImageAPI.src.Pen.getPenColor().
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine().
int MovementAndImageAPI.src.PenHandler.getPenPosition ()
Returns
0 if pen is up, 1 if pen is down
Definition at line 42 of file PenHandler.java.
References MovementAndImageAPI.src.Pen.getPenPosition().
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine(), and MovementAndImageAPI.src.Turtle.getPenPosition().
void MovementAndImageAPI.src.PenHandler.setLineWidth (double width)
Parameters
width the width of the pen in pixels
Definition at line 50 of file PenHandler.java.
References MovementAndImageAPI.src.Pen.setLineWidth().
Referenced by MovementAndImageAPI.src.TurtleHandler.setLineWidth().
void MovementAndImageAPI.src.PenHandler.setPenColor (Color newPenColor)
Parameters
newPenColor the color to set the Pen's color to.
Definition at line 17 of file PenHandler.java.
References MovementAndImageAPI.src.Pen.setPenColor().
Referenced by ColorFeature.changePenColor().
void MovementAndImageAPI.src.PenHandler.setPenPosition (int penPosition)
Parameters
penPosition 0 if pen is up, 1 if pen is down
Definition at line 26 of file PenHandler.java.
References MovementAndImageAPI.src.Pen.setPenPosition().
Referenced by MovementAndImageAPI.src.Turtle.setPenPosition().
Member Data Documentation
Pen MovementAndImageAPI.src.PenHandler.mainPen = new Pen() private
Definition at line 11 of file PenHandler.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/MovementAndImageAPI/src/PenHandler.java