slogo_team12: MovementAndImageAPI.src.Pen Class Reference
MovementAndImageAPI.src.Pen Class Reference
Public Member Functions
Pen ()
void setPenColor (Color newPenColor)
Color getPenColor ()
void setPenPosition (int penPosition)
int getPenPosition ()
void setLineWidth (double width)
double getLineWidth ()
Private Attributes
Color myPenColor
int myPenPosition
double myLineWidth
Detailed Description
Author
Eirika Sawh This class represents the Pen which has a color and an up or down position, used for checking how and whether or not lines should be drawn.
Definition at line 12 of file Pen.java.
Constructor & Destructor Documentation
MovementAndImageAPI.src.Pen.Pen ()
Definition at line 17 of file Pen.java.
Member Function Documentation
double MovementAndImageAPI.src.Pen.getLineWidth ()
Returns
the width of the pen in pixels
Definition at line 70 of file Pen.java.
References MovementAndImageAPI.src.Pen.myLineWidth.
Referenced by MovementAndImageAPI.src.PenHandler.getLineWidth().
Color MovementAndImageAPI.src.Pen.getPenColor ()
Returns
myPenColor (the current color)
Definition at line 36 of file Pen.java.
References MovementAndImageAPI.src.Pen.myPenColor.
Referenced by MovementAndImageAPI.src.PenHandler.getPenColor().
int MovementAndImageAPI.src.Pen.getPenPosition ()
Returns
0 if pen is up, 1 if pen is down
Definition at line 53 of file Pen.java.
References MovementAndImageAPI.src.Pen.myPenPosition.
Referenced by MovementAndImageAPI.src.PenHandler.getPenPosition().
void MovementAndImageAPI.src.Pen.setLineWidth (double width)
Parameters
width the width in pixels
Definition at line 62 of file Pen.java.
Referenced by MovementAndImageAPI.src.PenHandler.setLineWidth().
void MovementAndImageAPI.src.Pen.setPenColor (Color newPenColor)
Parameters
newPenColor the new color for the Pen
Definition at line 28 of file Pen.java.
Referenced by MovementAndImageAPI.src.PenHandler.setPenColor().
void MovementAndImageAPI.src.Pen.setPenPosition (int penPosition)
Parameters
penPosition 0 if pen is up, 1 if pen is down
Definition at line 45 of file Pen.java.
Referenced by MovementAndImageAPI.src.PenHandler.setPenPosition().
Member Data Documentation
double MovementAndImageAPI.src.Pen.myLineWidth private
Definition at line 15 of file Pen.java.
Referenced by MovementAndImageAPI.src.Pen.getLineWidth().
Color MovementAndImageAPI.src.Pen.myPenColor private
Definition at line 13 of file Pen.java.
Referenced by MovementAndImageAPI.src.Pen.getPenColor().
int MovementAndImageAPI.src.Pen.myPenPosition private
Definition at line 14 of file Pen.java.
Referenced by MovementAndImageAPI.src.Pen.getPenPosition().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/MovementAndImageAPI/src/Pen.java