/* Generated By:JavaCC: Do not edit this line. LogoParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int REPEAT = 5;
  /** RegularExpression Id. */
  int UNTIL = 6;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int IFELSE = 9;
  /** RegularExpression Id. */
  int LABEL = 10;
  /** RegularExpression Id. */
  int MAKE = 11;
  /** RegularExpression Id. */
  int TO = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int FORWARD = 14;
  /** RegularExpression Id. */
  int BACK = 15;
  /** RegularExpression Id. */
  int RIGHT = 16;
  /** RegularExpression Id. */
  int LEFT = 17;
  /** RegularExpression Id. */
  int CLEAR = 18;
  /** RegularExpression Id. */
  int PENUP = 19;
  /** RegularExpression Id. */
  int PENDOWN = 20;
  /** RegularExpression Id. */
  int HIDE = 21;
  /** RegularExpression Id. */
  int SHOW = 22;
  /** RegularExpression Id. */
  int HOME = 23;
  /** RegularExpression Id. */
  int SETXY = 24;
  /** RegularExpression Id. */
  int SETHEADING = 25;
  /** RegularExpression Id. */
  int TOWARDS = 26;
  /** RegularExpression Id. */
  int SETPENSIZE = 27;
  /** RegularExpression Id. */
  int NUM = 28;
  /** RegularExpression Id. */
  int SUM = 29;
  /** RegularExpression Id. */
  int SUB = 30;
  /** RegularExpression Id. */
  int MULT = 31;
  /** RegularExpression Id. */
  int DIV = 32;
  /** RegularExpression Id. */
  int POW = 33;
  /** RegularExpression Id. */
  int GT = 34;
  /** RegularExpression Id. */
  int LT = 35;
  /** RegularExpression Id. */
  int GE = 36;
  /** RegularExpression Id. */
  int LE = 37;
  /** RegularExpression Id. */
  int EQ = 38;
  /** RegularExpression Id. */
  int STRING = 39;
  /** RegularExpression Id. */
  int COLON = 40;
  /** RegularExpression Id. */
  int LBRACKET = 41;
  /** RegularExpression Id. */
  int RBRACKET = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<EOL>",
    "\"repeat\"",
    "\"until\"",
    "\"while\"",
    "\"if\"",
    "\"ifelse\"",
    "\"label\"",
    "\"make\"",
    "\"to\"",
    "\"end\"",
    "<FORWARD>",
    "<BACK>",
    "<RIGHT>",
    "<LEFT>",
    "<CLEAR>",
    "<PENUP>",
    "<PENDOWN>",
    "<HIDE>",
    "<SHOW>",
    "\"home\"",
    "<SETXY>",
    "<SETHEADING>",
    "\"towards\"",
    "<SETPENSIZE>",
    "<NUM>",
    "<SUM>",
    "<SUB>",
    "<MULT>",
    "<DIV>",
    "<POW>",
    "<GT>",
    "<LT>",
    "\" >=\"",
    "\" <=\"",
    "<EQ>",
    "<STRING>",
    "\":\"",
    "\"[\"",
    "\"]\"",
  };

}
