slogo_team12: parser.ParseException Class Reference
parser.ParseException Class Reference
Public Member Functions
ParseException (Token currentTokenVal, int[][] expectedTokenSequencesVal, String[] tokenImageVal)
ParseException ()
ParseException (String message)
Public Attributes
Token currentToken
int[][] expectedTokenSequences
String[] tokenImage
Protected Attributes
String eol = System.getProperty("line.separator", "\n")
Static Package Functions
static String add_escapes (String str)
Static Private Member Functions
static String initialise (Token currentToken, int[][] expectedTokenSequences, String[] tokenImage)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
This exception is thrown when parse errors are encountered. You can explicitly create objects of this exception type by calling the method generateParseException in the generated parser.
You can modify this class to customize your error reporting mechanisms so long as you retain the public fields.
Definition at line 14 of file ParseException.java.
Constructor & Destructor Documentation
parser.ParseException.ParseException (Token currentTokenVal, int expectedTokenSequencesVal[][], String[] tokenImageVal)
This constructor is used by the method "generateParseException" in the generated parser. Calling this constructor generates a new object of this type with the fields "currentToken", "expectedTokenSequences", and "tokenImage" set.
Definition at line 29 of file ParseException.java.
References parser.ParseException.currentToken, parser.ParseException.expectedTokenSequences, parser.ParseException.initialise(), and parser.ParseException.tokenImage.
parser.ParseException.ParseException ()
The following constructors are for use by you for whatever purpose you can think of. Constructing the exception in this manner makes the exception behave in the normal way - i.e., as documented in the class "Throwable". The fields "errorToken", "expectedTokenSequences", and "tokenImage" do not contain relevant information. The JavaCC generated code does not use these constructors.
Definition at line 50 of file ParseException.java.
parser.ParseException.ParseException (String message)
Constructor with message.
Definition at line 55 of file ParseException.java.
Member Function Documentation
static String parser.ParseException.add_escapes (String str) static package
Used to convert raw characters to their escaped version when these raw version cannot be used as part of an ASCII string literal.
Definition at line 141 of file ParseException.java.
Referenced by parser.ParseException.initialise().
static String parser.ParseException.initialise (Token currentToken, int expectedTokenSequences[][], String[] tokenImage) static private
It uses "currentToken" and "expectedTokenSequences" to generate a parse error message and returns it. If this object has been created due to a parse error, and you do not catch it (it gets thrown from the parser) the correct error message gets displayed.
Definition at line 88 of file ParseException.java.
References parser.ParseException.add_escapes(), parser.Token.beginColumn, parser.Token.beginLine, parser.ParseException.eol, parser.Token.image, parser.Token.kind, and parser.Token.next.
Referenced by parser.ParseException.ParseException().
Member Data Documentation
Token parser.ParseException.currentToken
This is the last token that has been consumed successfully. If this object has been created due to a parse error, the token followng this token will (therefore) be the first error token.
Definition at line 65 of file ParseException.java.
Referenced by parser.ParseException.ParseException().
String parser.ParseException.eol = System.getProperty("line.separator", "\n") protected
The end of line string for this machine.
Definition at line 134 of file ParseException.java.
Referenced by parser.ParseException.initialise().
int [][] parser.ParseException.expectedTokenSequences
Each entry in this array is an array of integers. Each array of integers represents a sequence of tokens (by their ordinal values) that is expected at this point of the parse.
Definition at line 72 of file ParseException.java.
Referenced by parser.ParseException.ParseException().
final long parser.ParseException.serialVersionUID = 1L static private
The version identifier for this Serializable class. Increment only if the serialized form of the class changes.
Definition at line 21 of file ParseException.java.
String [] parser.ParseException.tokenImage
This is a reference to the "tokenImage" array of the generated parser within which the parse error occurred. This array is defined in the generated ...Constants interface.
Definition at line 79 of file ParseException.java.
Referenced by parser.ParseException.ParseException().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/parser/ParseException.java