slogo_team12: parser.SimpleCharStream Class Reference
parser.SimpleCharStream Class Reference
Public Member Functions
char BeginToken () throws java.io.IOException
char readChar () throws java.io.IOException
int getColumn ()
int getLine ()
int getEndColumn ()
int getEndLine ()
int getBeginColumn ()
int getBeginLine ()
void backup (int amount)
SimpleCharStream (java.io.Reader dstream, int startline, int startcolumn, int buffersize)
SimpleCharStream (java.io.Reader dstream, int startline, int startcolumn)
SimpleCharStream (java.io.Reader dstream)
void ReInit (java.io.Reader dstream, int startline, int startcolumn, int buffersize)
void ReInit (java.io.Reader dstream, int startline, int startcolumn)
void ReInit (java.io.Reader dstream)
SimpleCharStream (java.io.InputStream dstream, String encoding, int startline, int startcolumn, int buffersize) throws java.io.UnsupportedEncodingException
SimpleCharStream (java.io.InputStream dstream, int startline, int startcolumn, int buffersize)
SimpleCharStream (java.io.InputStream dstream, String encoding, int startline, int startcolumn) throws java.io.UnsupportedEncodingException
SimpleCharStream (java.io.InputStream dstream, int startline, int startcolumn)
SimpleCharStream (java.io.InputStream dstream, String encoding) throws java.io.UnsupportedEncodingException
SimpleCharStream (java.io.InputStream dstream)
void ReInit (java.io.InputStream dstream, String encoding, int startline, int startcolumn, int buffersize) throws java.io.UnsupportedEncodingException
void ReInit (java.io.InputStream dstream, int startline, int startcolumn, int buffersize)
void ReInit (java.io.InputStream dstream, String encoding) throws java.io.UnsupportedEncodingException
void ReInit (java.io.InputStream dstream)
void ReInit (java.io.InputStream dstream, String encoding, int startline, int startcolumn) throws java.io.UnsupportedEncodingException
void ReInit (java.io.InputStream dstream, int startline, int startcolumn)
String GetImage ()
char[] GetSuffix (int len)
void Done ()
void adjustBeginLineColumn (int newLine, int newCol)
Public Attributes
int bufpos = -1
Static Public Attributes
static final boolean staticFlag = false
Protected Member Functions
void setTabSize (int i)
int getTabSize (int i)
void ExpandBuff (boolean wrapAround)
void FillBuff () throws java.io.IOException
void UpdateLineColumn (char c)
Protected Attributes
int bufline []
int bufcolumn []
int column = 0
int line = 1
boolean prevCharIsCR = false
boolean prevCharIsLF = false
java.io.Reader inputStream
char[] buffer
int maxNextCharInd = 0
int inBuf = 0
int tabSize = 8
Package Attributes
int bufsize
int available
int tokenBegin
Detailed Description
An implementation of interface CharStream, where the stream is assumed to contain only ASCII characters (without unicode processing).
Definition at line 10 of file SimpleCharStream.java.
Constructor & Destructor Documentation
parser.SimpleCharStream.SimpleCharStream (java.io.Reader dstream, int startline, int startcolumn, int buffersize)
Constructor.
Definition at line 253 of file SimpleCharStream.java.
References parser.SimpleCharStream.inputStream.
parser.SimpleCharStream.SimpleCharStream (java.io.Reader dstream, int startline, int startcolumn)
Constructor.
Definition at line 267 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.Reader dstream)
Constructor.
Definition at line 274 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.InputStream dstream, String encoding, int startline, int startcolumn, int buffersize) throws java.io.UnsupportedEncodingException
Constructor.
Definition at line 312 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.InputStream dstream, int startline, int startcolumn, int buffersize)
Constructor.
Definition at line 319 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.InputStream dstream, String encoding, int startline, int startcolumn) throws java.io.UnsupportedEncodingException
Constructor.
Definition at line 326 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.InputStream dstream, int startline, int startcolumn)
Constructor.
Definition at line 333 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.InputStream dstream, String encoding) throws java.io.UnsupportedEncodingException
Constructor.
Definition at line 340 of file SimpleCharStream.java.
parser.SimpleCharStream.SimpleCharStream (java.io.InputStream dstream)
Constructor.
Definition at line 346 of file SimpleCharStream.java.
Member Function Documentation
void parser.SimpleCharStream.adjustBeginLineColumn (int newLine, int newCol)
Method to adjust line and column numbers for the start of a token.
Definition at line 426 of file SimpleCharStream.java.
References parser.SimpleCharStream.inBuf, and parser.SimpleCharStream.tokenBegin.
void parser.SimpleCharStream.backup (int amount)
Backup a number of characters.
Definition at line 245 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufsize.
Referenced by parser.SimpleCharStream.FillBuff(), and parser.LogoParserTokenManager.getNextToken().
char parser.SimpleCharStream.BeginToken () throws java.io.IOException
Start.
Definition at line 133 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos, and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.getNextToken().
void parser.SimpleCharStream.Done ()
Reset buffer when finished.
Definition at line 416 of file SimpleCharStream.java.
void parser.SimpleCharStream.ExpandBuff (boolean wrapAround) protected
Definition at line 39 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufsize, and parser.SimpleCharStream.tokenBegin.
Referenced by parser.SimpleCharStream.FillBuff().
void parser.SimpleCharStream.FillBuff () throws java.io.IOException protected
Definition at line 88 of file SimpleCharStream.java.
References parser.SimpleCharStream.backup(), parser.SimpleCharStream.bufpos, parser.SimpleCharStream.bufsize, parser.SimpleCharStream.ExpandBuff(), parser.SimpleCharStream.inputStream, and parser.SimpleCharStream.tokenBegin.
Referenced by parser.SimpleCharStream.readChar().
int parser.SimpleCharStream.getBeginColumn ()
Get token beginning column number.
Definition at line 235 of file SimpleCharStream.java.
References parser.SimpleCharStream.tokenBegin.
Referenced by parser.LogoParserTokenManager.jjFillToken().
int parser.SimpleCharStream.getBeginLine ()
Get token beginning line number.
Definition at line 240 of file SimpleCharStream.java.
References parser.SimpleCharStream.tokenBegin.
Referenced by parser.LogoParserTokenManager.jjFillToken().
int parser.SimpleCharStream.getColumn ()
Deprecated:
See also
getEndColumn
Definition at line 210 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos.
int parser.SimpleCharStream.getEndColumn ()
Get token end column number.
Definition at line 225 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos.
Referenced by parser.LogoParserTokenManager.getNextToken(), and parser.LogoParserTokenManager.jjFillToken().
int parser.SimpleCharStream.getEndLine ()
Get token end line number.
Definition at line 230 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos.
Referenced by parser.LogoParserTokenManager.getNextToken(), and parser.LogoParserTokenManager.jjFillToken().
String parser.SimpleCharStream.GetImage ()
Get token literal value.
Definition at line 389 of file SimpleCharStream.java.
Referenced by parser.LogoParserTokenManager.getNextToken(), and parser.LogoParserTokenManager.jjFillToken().
int parser.SimpleCharStream.getLine ()
Deprecated:
See also
getEndLine
Definition at line 220 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos.
char [] parser.SimpleCharStream.GetSuffix (int len)
Get the suffix.
Definition at line 399 of file SimpleCharStream.java.
int parser.SimpleCharStream.getTabSize (int i) protected
Definition at line 36 of file SimpleCharStream.java.
References parser.SimpleCharStream.tabSize.
char parser.SimpleCharStream.readChar () throws java.io.IOException
Read a character.
Definition at line 183 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos, parser.SimpleCharStream.FillBuff(), parser.SimpleCharStream.inBuf, and parser.SimpleCharStream.UpdateLineColumn().
Referenced by parser.SimpleCharStream.BeginToken(), parser.LogoParserTokenManager.getNextToken(), parser.LogoParserTokenManager.jjMoveNfa_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0(), and parser.LogoParserTokenManager.jjStartNfaWithStates_0().
void parser.SimpleCharStream.ReInit (java.io.Reader dstream, int startline, int startcolumn, int buffersize)
Reinitialise.
Definition at line 280 of file SimpleCharStream.java.
References parser.SimpleCharStream.inputStream.
Referenced by parser.SimpleCharStream.ReInit(), and parser.LogoParser.ReInit().
void parser.SimpleCharStream.ReInit (java.io.Reader dstream, int startline, int startcolumn)
Reinitialise.
Definition at line 300 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.Reader dstream)
Reinitialise.
Definition at line 307 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.InputStream dstream, String encoding, int startline, int startcolumn, int buffersize) throws java.io.UnsupportedEncodingException
Reinitialise.
Definition at line 352 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.InputStream dstream, int startline, int startcolumn, int buffersize)
Reinitialise.
Definition at line 359 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.InputStream dstream, String encoding) throws java.io.UnsupportedEncodingException
Reinitialise.
Definition at line 366 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.InputStream dstream)
Reinitialise.
Definition at line 372 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.InputStream dstream, String encoding, int startline, int startcolumn) throws java.io.UnsupportedEncodingException
Reinitialise.
Definition at line 377 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.ReInit (java.io.InputStream dstream, int startline, int startcolumn)
Reinitialise.
Definition at line 383 of file SimpleCharStream.java.
References parser.SimpleCharStream.ReInit().
void parser.SimpleCharStream.setTabSize (int i) protected
Definition at line 35 of file SimpleCharStream.java.
void parser.SimpleCharStream.UpdateLineColumn (char c) protected
Definition at line 142 of file SimpleCharStream.java.
References parser.SimpleCharStream.bufpos, parser.SimpleCharStream.column, parser.SimpleCharStream.line, and parser.SimpleCharStream.tabSize.
Referenced by parser.SimpleCharStream.readChar().
Member Data Documentation
int parser.SimpleCharStream.available package
Definition at line 15 of file SimpleCharStream.java.
int parser.SimpleCharStream.bufcolumn[] protected
Definition at line 20 of file SimpleCharStream.java.
char [] parser.SimpleCharStream.buffer protected
Definition at line 30 of file SimpleCharStream.java.
int parser.SimpleCharStream.bufline[] protected
Definition at line 19 of file SimpleCharStream.java.
int parser.SimpleCharStream.bufpos = -1
Position in buffer.
Definition at line 18 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.BeginToken(), parser.SimpleCharStream.FillBuff(), parser.SimpleCharStream.getColumn(), parser.SimpleCharStream.getEndColumn(), parser.SimpleCharStream.getEndLine(), parser.SimpleCharStream.getLine(), parser.SimpleCharStream.readChar(), and parser.SimpleCharStream.UpdateLineColumn().
int parser.SimpleCharStream.bufsize package
Definition at line 14 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.backup(), parser.SimpleCharStream.ExpandBuff(), and parser.SimpleCharStream.FillBuff().
int parser.SimpleCharStream.column = 0 protected
Definition at line 22 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.UpdateLineColumn().
int parser.SimpleCharStream.inBuf = 0 protected
Definition at line 32 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.adjustBeginLineColumn(), and parser.SimpleCharStream.readChar().
java.io.Reader parser.SimpleCharStream.inputStream protected
Definition at line 28 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.FillBuff(), parser.SimpleCharStream.ReInit(), and parser.SimpleCharStream.SimpleCharStream().
int parser.SimpleCharStream.line = 1 protected
Definition at line 23 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.UpdateLineColumn().
int parser.SimpleCharStream.maxNextCharInd = 0 protected
Definition at line 31 of file SimpleCharStream.java.
boolean parser.SimpleCharStream.prevCharIsCR = false protected
Definition at line 25 of file SimpleCharStream.java.
boolean parser.SimpleCharStream.prevCharIsLF = false protected
Definition at line 26 of file SimpleCharStream.java.
final boolean parser.SimpleCharStream.staticFlag = false static
Whether parser is static.
Definition at line 13 of file SimpleCharStream.java.
Referenced by parser.LogoParserTokenManager.LogoParserTokenManager().
int parser.SimpleCharStream.tabSize = 8 protected
Definition at line 33 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.getTabSize(), and parser.SimpleCharStream.UpdateLineColumn().
int parser.SimpleCharStream.tokenBegin package
Definition at line 16 of file SimpleCharStream.java.
Referenced by parser.SimpleCharStream.adjustBeginLineColumn(), parser.SimpleCharStream.ExpandBuff(), parser.SimpleCharStream.FillBuff(), parser.SimpleCharStream.getBeginColumn(), and parser.SimpleCharStream.getBeginLine().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/parser/SimpleCharStream.java