slogo_team12: MovementAndImageAPI.src.Turtle Class Reference
MovementAndImageAPI.src.Turtle Class Reference
Public Member Functions
Turtle ()
void updateOrientation (double orientation)
void updateAbsoluteOrientation (double newAngle)
void updateLocation (double translocation)
void updateAbsoluteLocation (Point2D newLocation)
void updateImage (Image newImage)
void setPenPosition (int penPosition)
Point2D getPoint ()
double getOrientation ()
ImageView getImage ()
int getPenPosition ()
void show (int show)
PenHandler getPenHandler ()
Private Member Functions
void ensurePositiveOrientation ()
void finishRotation ()
Private Attributes
Point2D myLocation
double myOrientation
ImageView myImage
PenHandler myPenHandler
Static Private Attributes
static final double TOTAL_NUMBER_OF_DEGREES = 360
Detailed Description
Author
Eirika Sawh This class is the actual visual representation of the Turtle.
Definition at line 12 of file Turtle.java.
Constructor & Destructor Documentation
MovementAndImageAPI.src.Turtle.Turtle ()
Definition at line 20 of file Turtle.java.
Member Function Documentation
void MovementAndImageAPI.src.Turtle.ensurePositiveOrientation () private
Ensures a positive orientation angle (ex: 359 degrees instead of -1 degree) for clarity
Definition at line 41 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.TOTAL_NUMBER_OF_DEGREES.
Referenced by MovementAndImageAPI.src.Turtle.finishRotation().
void MovementAndImageAPI.src.Turtle.finishRotation () private
Makes sure the orientation is a positive angle, then rotates the imageview accordingly.
Definition at line 61 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.ensurePositiveOrientation().
Referenced by MovementAndImageAPI.src.Turtle.updateAbsoluteOrientation(), and MovementAndImageAPI.src.Turtle.updateOrientation().
ImageView MovementAndImageAPI.src.Turtle.getImage ()
Returns
myImage
Definition at line 124 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.myImage.
Referenced by MovementAndImageAPI.src.TurtleHandler.getShowing(), MovementAndImageAPI.src.TurtleHandler.moveAndDraw(), MovementAndImageAPI.src.TurtleHandler.showTurtle(), MovementAndImageAPI.src.TurtleHandler.updateImage(), MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteOrientation(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleOrientation().
double MovementAndImageAPI.src.Turtle.getOrientation ()
Returns
the Turtle's orientation angle
Definition at line 116 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.myOrientation.
Referenced by MovementAndImageAPI.src.TurtleHandler.getOrientation().
PenHandler MovementAndImageAPI.src.Turtle.getPenHandler ()
Returns
the Turtle's PenHandler
Definition at line 150 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.myPenHandler.
Referenced by MovementAndImageAPI.src.TurtleHandler.getPenHandler(), MovementAndImageAPI.src.TurtleHandler.moveAndDraw(), and MovementAndImageAPI.src.TurtleHandler.setLineWidth().
int MovementAndImageAPI.src.Turtle.getPenPosition ()
Returns
0 if pen is up, 1 if pen is down
Definition at line 132 of file Turtle.java.
References MovementAndImageAPI.src.PenHandler.getPenPosition().
Referenced by MovementAndImageAPI.src.TurtleHandler.getPenPosition(), and MovementAndImageAPI.src.TurtleHandler.moveAndDraw().
Point2D MovementAndImageAPI.src.Turtle.getPoint ()
Returns
the Turtle's current point
Definition at line 108 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.myLocation.
Referenced by MovementAndImageAPI.src.TurtleHandler.getTurtleLocation(), MovementAndImageAPI.src.TurtleHandler.getTurtleLocationInCanvas(), MovementAndImageAPI.src.TurtleHandler.showTurtle(), MovementAndImageAPI.src.TurtleTest.testMovingDirections(), MovementAndImageAPI.src.TurtleHandler.updateImage(), MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteLocation(), MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteOrientation(), MovementAndImageAPI.src.TurtleHandler.updateTurtleLocation(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleOrientation().
void MovementAndImageAPI.src.Turtle.setPenPosition (int penPosition)
Parameters
penPosition 0 if pen is up, 1 if pen is down
Definition at line 100 of file Turtle.java.
References MovementAndImageAPI.src.PenHandler.setPenPosition().
Referenced by MovementAndImageAPI.src.TurtleHandler.setPenPosition().
void MovementAndImageAPI.src.Turtle.show (int show)
Parameters
show 1 if should show the turtle, 0 if should hide the turtle
Definition at line 139 of file Turtle.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.showTurtle().
void MovementAndImageAPI.src.Turtle.updateAbsoluteLocation (Point2D newLocation)
Parameters
newLocation The location to instantly move to.
Definition at line 84 of file Turtle.java.
Referenced by MovementAndImageAPI.src.TurtleTest.testMovingDirections(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteLocation().
void MovementAndImageAPI.src.Turtle.updateAbsoluteOrientation (double newAngle)
Parameters
newAngle The angle to immediately change to.
Definition at line 52 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.finishRotation(), and MovementAndImageAPI.src.Turtle.TOTAL_NUMBER_OF_DEGREES.
Referenced by MovementAndImageAPI.src.TurtleTest.testMovingDirections(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteOrientation().
void MovementAndImageAPI.src.Turtle.updateImage (Image newImage)
Parameters
newImage the new Image to set the Turtle's image to
Definition at line 92 of file Turtle.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.updateImage().
void MovementAndImageAPI.src.Turtle.updateLocation (double translocation)
Parameters
translocation How many pixels to move in that direction. Uses Math and orientation to figure out how many pixels that is in the X and Y directions.
Definition at line 73 of file Turtle.java.
Referenced by MovementAndImageAPI.src.TurtleTest.testMovingDirections(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleLocation().
void MovementAndImageAPI.src.Turtle.updateOrientation (double orientation)
Parameters
orientation The amount to add to the current orientation/angle
Definition at line 32 of file Turtle.java.
References MovementAndImageAPI.src.Turtle.finishRotation().
Referenced by MovementAndImageAPI.src.TurtleHandler.updateTurtleOrientation().
Member Data Documentation
ImageView MovementAndImageAPI.src.Turtle.myImage private
Definition at line 17 of file Turtle.java.
Referenced by MovementAndImageAPI.src.Turtle.getImage().
Point2D MovementAndImageAPI.src.Turtle.myLocation private
Definition at line 15 of file Turtle.java.
Referenced by MovementAndImageAPI.src.Turtle.getPoint().
double MovementAndImageAPI.src.Turtle.myOrientation private
Definition at line 16 of file Turtle.java.
Referenced by MovementAndImageAPI.src.Turtle.getOrientation().
PenHandler MovementAndImageAPI.src.Turtle.myPenHandler private
Definition at line 18 of file Turtle.java.
Referenced by MovementAndImageAPI.src.Turtle.getPenHandler().
final double MovementAndImageAPI.src.Turtle.TOTAL_NUMBER_OF_DEGREES = 360 static private
Definition at line 14 of file Turtle.java.
Referenced by MovementAndImageAPI.src.Turtle.ensurePositiveOrientation(), and MovementAndImageAPI.src.Turtle.updateAbsoluteOrientation().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/MovementAndImageAPI/src/Turtle.java