slogo_team12: parser.TokenMgrError Class Reference
parser.TokenMgrError Class Reference
Public Member Functions
String getMessage ()
TokenMgrError ()
TokenMgrError (String message, int reason)
TokenMgrError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar, int reason)
Static Protected Member Functions
static final String addEscapes (String str)
static String LexicalError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar)
Package Attributes
int errorCode
Static Package Attributes
static final int LEXICAL_ERROR = 0
static final int STATIC_LEXER_ERROR = 1
static final int INVALID_LEXICAL_STATE = 2
static final int LOOP_DETECTED = 3
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Token Manager Error.
Definition at line 6 of file TokenMgrError.java.
Constructor & Destructor Documentation
parser.TokenMgrError.TokenMgrError ()
No arg constructor.
Definition at line 133 of file TokenMgrError.java.
parser.TokenMgrError.TokenMgrError (String message, int reason)
Constructor with message and reason.
Definition at line 137 of file TokenMgrError.java.
parser.TokenMgrError.TokenMgrError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar, int reason)
Full Constructor.
Definition at line 143 of file TokenMgrError.java.
References parser.TokenMgrError.LexicalError().
Member Function Documentation
static final String parser.TokenMgrError.addEscapes (String str) static protected
Replaces unprintable characters by their escaped (or unicode escaped) equivalents in the given string
Definition at line 50 of file TokenMgrError.java.
Referenced by parser.TokenMgrError.LexicalError().
String parser.TokenMgrError.getMessage ()
You can also modify the body of this method to customize your error messages. For example, cases like LOOP_DETECTED and INVALID_LEXICAL_STATE are not of end-users concern, so you can return something like :
"Internal Error : Please file a bug report .... "
from this method for such cases in the release version of your parser.
Definition at line 124 of file TokenMgrError.java.
static String parser.TokenMgrError.LexicalError (boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar) static protected
Returns a detailed message for the Error when it is thrown by the token manager to indicate a lexical error. Parameters : EOFSeen : indicates if EOF caused the lexical error curLexState : lexical state in which this error occurred errorLine : line number when the error occurred errorColumn : column number when the error occurred errorAfter : prefix that was seen before this error occurred curchar : the offending character Note: You can customize the lexical error message by modifying this method.
Definition at line 107 of file TokenMgrError.java.
References parser.TokenMgrError.addEscapes().
Referenced by parser.TokenMgrError.TokenMgrError().
Member Data Documentation
int parser.TokenMgrError.errorCode package
Indicates the reason why the exception is thrown. It will have one of the above 4 values.
Definition at line 44 of file TokenMgrError.java.
final int parser.TokenMgrError.INVALID_LEXICAL_STATE = 2 static package
Tried to change to an invalid lexical state.
Definition at line 33 of file TokenMgrError.java.
Referenced by parser.LogoParserTokenManager.SwitchTo().
final int parser.TokenMgrError.LEXICAL_ERROR = 0 static package
Lexical error occurred.
Definition at line 23 of file TokenMgrError.java.
Referenced by parser.LogoParserTokenManager.getNextToken().
final int parser.TokenMgrError.LOOP_DETECTED = 3 static package
Detected (and bailed out of) an infinite loop in the token manager.
Definition at line 38 of file TokenMgrError.java.
final long parser.TokenMgrError.serialVersionUID = 1L static private
The version identifier for this Serializable class. Increment only if the serialized form of the class changes.
Definition at line 14 of file TokenMgrError.java.
final int parser.TokenMgrError.STATIC_LEXER_ERROR = 1 static package
An attempt was made to create a second instance of a static token manager.
Definition at line 28 of file TokenMgrError.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/parser/TokenMgrError.java