slogo_team12: MovementAndImageAPI.src.GeneralTurtleHandler Class Reference
MovementAndImageAPI.src.GeneralTurtleHandler Class Reference abstract
Public Member Functions
abstract double getOrientation ()
abstract Point2D getTurtleLocation ()
abstract void updateTurtleLocation (double translocation)
abstract void updateTurtleAbsoluteLocation (Point2D newLocation)
abstract void updateTurtleOrientation (double rotation)
abstract void updateTurtleAbsoluteOrientation (double newAngle)
abstract void showTurtle (int show)
abstract void updateImage (Image newImage)
abstract void clearLines ()
abstract void setPenPosition (int penPosition)
abstract int getPenPosition ()
abstract int getShowing ()
abstract PenHandler getPenHandler ()
abstract void setLineWidth (double width)
abstract void towards (Point2D location)
Detailed Description
Definition at line 6 of file GeneralTurtleHandler.java.
Member Function Documentation
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.clearLines () abstract
Clears the lines associated with the Turtle.
Referenced by commands.MovementCommand.execute().
abstract double MovementAndImageAPI.src.GeneralTurtleHandler.getOrientation () abstract
Returns
the Turtle's current orientation angle.
abstract PenHandler MovementAndImageAPI.src.GeneralTurtleHandler.getPenHandler () abstract
Returns
the PenHandler associated with the Turtle
abstract int MovementAndImageAPI.src.GeneralTurtleHandler.getPenPosition () abstract
Returns
0 if pen is up, 1 if pen is down
abstract int MovementAndImageAPI.src.GeneralTurtleHandler.getShowing () abstract
Returns
1 if the turtle is showing (visible), 0 if hiding (invisible)
abstract Point2D MovementAndImageAPI.src.GeneralTurtleHandler.getTurtleLocation () abstract
Returns
the Point2D associated with the Turtle's actual location, regardless of the bounds of the canvas it's in.
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.setLineWidth (double width) abstract
Parameters
width the line width in pixels
Referenced by commands.MovementCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.setPenPosition (int penPosition) abstract
Parameters
penPosition 0 if pen is up, 1 if pen is down
Referenced by commands.ActivityCommand.execute(), and commands.MovementCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.showTurtle (int show) abstract
Parameters
show 1 if should show the turtle, 0 if should hide the turtle
Referenced by commands.ActivityCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.towards (Point2D location) abstract
Parameters
location the point to be looking towards. If the location is outside the canvas, the turtle faces where that point would lie outside of the canvas (the destination doesn't loop to fit within the canvas).
Referenced by commands.MovementCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.updateImage (Image newImage) abstract
Parameters
newImage The new image to be drawn on the turtle's canvas
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.updateTurtleAbsoluteLocation (Point2D newLocation) abstract
Parameters
newLocation the location to instantly move to.
Referenced by commands.MovementCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.updateTurtleAbsoluteOrientation (double newAngle) abstract
Parameters
newAngle the orientation angle to immediately change to.
Referenced by commands.MovementCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.updateTurtleLocation (double translocation) abstract
Parameters
translocation the double amount of how many pixels to move forwards. Positive = move forwards, negative = move backwards
Referenced by commands.MovementCommand.execute().
abstract void MovementAndImageAPI.src.GeneralTurtleHandler.updateTurtleOrientation (double rotation) abstract
Parameters
rotation the amount of degrees to rotate the Turtle (clockwise)
Referenced by commands.MovementCommand.execute().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/MovementAndImageAPI/src/GeneralTurtleHandler.java