slogo_team12: MovementAndImageAPI.src.ImageUpdater Class Reference
MovementAndImageAPI.src.ImageUpdater Class Reference
Public Member Functions
ImageUpdater (Canvas turtleCanvas, Canvas lineCanvas)
void updateTurtleImage (Point2D newLocation, ImageView turtleImage)
void drawLine (Point2D from, Point2D to, PenHandler mainPenHandler)
Point2D getTurtleCanvasSize ()
void clearLines ()
Package Attributes
Canvas myLineCanvas
GraphicsContext lineGC
Static Package Attributes
static double Y_OFFSET
Private Member Functions
double ensurePositive (double numToCheck, double maxSize)
void drawRotatedImage (ImageView turtleImage, Point2D destination)
void rotate (double rotationAngle, double xPivot, double yPivot)
Point2D findNewStartPoint (Point2D boundary)
Point2D findBoundaryPoint (Point2D startPoint, Point2D endPoint)
Point2D yBoundary (Point2D startPoint, Point2D endPoint, double slope)
Point2D xBoundary (Point2D startPoint, Point2D endPoint, double slope)
boolean xOutOfBounds (Point2D endPoint)
boolean yOutOfBounds (Point2D endPoint)
Private Attributes
Canvas myTurtleCanvas
GraphicsContext turtleGC
Static Private Attributes
static double X_OFFSET
Detailed Description
Author
Eirika Sawh This class updates the actual image placement in the Scene.
Definition at line 19 of file ImageUpdater.java.
Constructor & Destructor Documentation
MovementAndImageAPI.src.ImageUpdater.ImageUpdater (Canvas turtleCanvas, Canvas lineCanvas)
Definition at line 24 of file ImageUpdater.java.
Member Function Documentation
void MovementAndImageAPI.src.ImageUpdater.clearLines ()
Clears all lines drawn by the Turtle
Definition at line 236 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.clearLines().
void MovementAndImageAPI.src.ImageUpdater.drawLine (Point2D from, Point2D to, PenHandler mainPenHandler)
Parameters
from the starting point of the line
to the ending point of the line
mainPenHandler the PenHandler associated with the Turtle that is being drawn
Definition at line 94 of file ImageUpdater.java.
References MovementAndImageAPI.src.ImageUpdater.ensurePositive(), MovementAndImageAPI.src.ImageUpdater.findBoundaryPoint(), MovementAndImageAPI.src.ImageUpdater.findNewStartPoint(), MovementAndImageAPI.src.PenHandler.getLineWidth(), MovementAndImageAPI.src.PenHandler.getPenColor(), MovementAndImageAPI.src.PenHandler.getPenPosition(), MovementAndImageAPI.src.ImageUpdater.X_OFFSET, MovementAndImageAPI.src.ImageUpdater.xOutOfBounds(), MovementAndImageAPI.src.ImageUpdater.Y_OFFSET, and MovementAndImageAPI.src.ImageUpdater.yOutOfBounds().
Referenced by MovementAndImageAPI.src.TurtleHandler.moveAndDraw().
void MovementAndImageAPI.src.ImageUpdater.drawRotatedImage (ImageView turtleImage, Point2D destination) private
Parameters
turtleImage the image to draw
destination the location to draw the image
Definition at line 69 of file ImageUpdater.java.
References MovementAndImageAPI.src.ImageUpdater.rotate().
Referenced by MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
double MovementAndImageAPI.src.ImageUpdater.ensurePositive (double numToCheck, double maxSize) private
Definition at line 55 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
Point2D MovementAndImageAPI.src.ImageUpdater.findBoundaryPoint (Point2D startPoint, Point2D endPoint) private
Parameters
startPoint the starting point of the line
endPoint the ending point of the line
Returns
where the line goes out of the canvas bounds, or simply the endPoint if it doesn't go outside of the bounds
Definition at line 164 of file ImageUpdater.java.
References MovementAndImageAPI.src.ImageUpdater.xBoundary(), MovementAndImageAPI.src.ImageUpdater.xOutOfBounds(), MovementAndImageAPI.src.ImageUpdater.yBoundary(), and MovementAndImageAPI.src.ImageUpdater.yOutOfBounds().
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine().
Point2D MovementAndImageAPI.src.ImageUpdater.findNewStartPoint (Point2D boundary) private
Parameters
boundary where the line hits the edge of the canvas
Returns
the point where the line would loop around from
Definition at line 137 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine().
Point2D MovementAndImageAPI.src.ImageUpdater.getTurtleCanvasSize ()
Returns
a Point2D with the x being the turtle canvas width, the y being the turtle canvas height
Definition at line 228 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.getTurtleLocationInCanvas().
void MovementAndImageAPI.src.ImageUpdater.rotate (double rotationAngle, double xPivot, double yPivot) private
Definition at line 79 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawRotatedImage().
void MovementAndImageAPI.src.ImageUpdater.updateTurtleImage (Point2D newLocation, ImageView turtleImage)
Parameters
newLocation the location to move the Turtle's image to.
turtleImage the actual image to draw/move
Definition at line 40 of file ImageUpdater.java.
References MovementAndImageAPI.src.ImageUpdater.drawRotatedImage(), MovementAndImageAPI.src.ImageUpdater.ensurePositive(), MovementAndImageAPI.src.ImageUpdater.X_OFFSET, and MovementAndImageAPI.src.ImageUpdater.Y_OFFSET.
Referenced by MovementAndImageAPI.src.TurtleHandler.moveAndDraw(), MovementAndImageAPI.src.TurtleHandler.showTurtle(), MovementAndImageAPI.src.TurtleHandler.updateImage(), MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteOrientation(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleOrientation().
Point2D MovementAndImageAPI.src.ImageUpdater.xBoundary (Point2D startPoint, Point2D endPoint, double slope) private
Definition at line 202 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.findBoundaryPoint().
boolean MovementAndImageAPI.src.ImageUpdater.xOutOfBounds (Point2D endPoint) private
Definition at line 214 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine(), and MovementAndImageAPI.src.ImageUpdater.findBoundaryPoint().
Point2D MovementAndImageAPI.src.ImageUpdater.yBoundary (Point2D startPoint, Point2D endPoint, double slope) private
Definition at line 190 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.findBoundaryPoint().
boolean MovementAndImageAPI.src.ImageUpdater.yOutOfBounds (Point2D endPoint) private
Definition at line 218 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine(), and MovementAndImageAPI.src.ImageUpdater.findBoundaryPoint().
Member Data Documentation
GraphicsContext MovementAndImageAPI.src.ImageUpdater.lineGC package
Definition at line 21 of file ImageUpdater.java.
Canvas MovementAndImageAPI.src.ImageUpdater.myLineCanvas package
Definition at line 20 of file ImageUpdater.java.
Canvas MovementAndImageAPI.src.ImageUpdater.myTurtleCanvas private
Definition at line 20 of file ImageUpdater.java.
GraphicsContext MovementAndImageAPI.src.ImageUpdater.turtleGC private
Definition at line 21 of file ImageUpdater.java.
double MovementAndImageAPI.src.ImageUpdater.X_OFFSET static private
Definition at line 22 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
double MovementAndImageAPI.src.ImageUpdater.Y_OFFSET static package
Definition at line 22 of file ImageUpdater.java.
Referenced by MovementAndImageAPI.src.ImageUpdater.drawLine(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/MovementAndImageAPI/src/ImageUpdater.java