slogo_team12: commands.ICommand Interface Reference
commands.ICommand Interface Reference
Public Member Functions
void execute ()
Detailed Description
Definition at line 3 of file ICommand.java.
Member Function Documentation
void commands.ICommand.execute ()
Implemented in commands.MovementCommand, commands.ActivityCommand, commands.CommandsQueue, commands.CommandMake, commands.CommandExecute, and commands.CommandsRepeat.
Referenced by commands.CommandExecute.execute(), commands.CommandsRepeat.execute(), commands.CommandMake.execute(), Workspace.sendUserInput(), and Workspace.setUpPreviousCommands().
The documentation for this interface was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/commands/ICommand.java