slogo_team12: parser.LogoParserTokenManager Class Reference
parser.LogoParserTokenManager Class Reference
Public Member Functions
void setDebugStream (java.io.PrintStream ds)
LogoParserTokenManager (SimpleCharStream stream)
LogoParserTokenManager (SimpleCharStream stream, int lexState)
void ReInit (SimpleCharStream stream)
void ReInit (SimpleCharStream stream, int lexState)
void SwitchTo (int lexState)
Token getNextToken ()
Public Attributes
java.io.PrintStream debugStream = System.out
Public Attributes inherited from parser.LogoParserConstants
int EOF = 0
int EOL = 4
int REPEAT = 5
int UNTIL = 6
int WHILE = 7
int IF = 8
int IFELSE = 9
int LABEL = 10
int MAKE = 11
int TO = 12
int END = 13
int FORWARD = 14
int BACK = 15
int RIGHT = 16
int LEFT = 17
int CLEAR = 18
int PENUP = 19
int PENDOWN = 20
int HIDE = 21
int SHOW = 22
int HOME = 23
int SETXY = 24
int SETHEADING = 25
int TOWARDS = 26
int SETPENSIZE = 27
int NUM = 28
int SUM = 29
int SUB = 30
int MULT = 31
int DIV = 32
int POW = 33
int GT = 34
int LT = 35
int GE = 36
int LE = 37
int EQ = 38
int STRING = 39
int COLON = 40
int LBRACKET = 41
int RBRACKET = 42
int DEFAULT = 0
String[] tokenImage
Static Public Attributes
static final String[] jjstrLiteralImages
static final String[] lexStateNames
Protected Member Functions
Token jjFillToken ()
Static Protected Attributes
static SimpleCharStream input_stream
static char curChar
Package Attributes
int curLexState = 0
int defaultLexState = 0
int jjnewStateCnt
int jjround
int jjmatchedPos
int jjmatchedKind
Static Package Attributes
static final int[] jjnextStates
static final long[] jjtoToken
static final long[] jjtoSkip
Private Member Functions
final int jjStopStringLiteralDfa_0 (int pos, long active0)
final int jjStartNfa_0 (int pos, long active0)
int jjStopAtPos (int pos, int kind)
int jjMoveStringLiteralDfa0_0 ()
int jjMoveStringLiteralDfa1_0 (long active0)
int jjMoveStringLiteralDfa2_0 (long old0, long active0)
int jjMoveStringLiteralDfa3_0 (long old0, long active0)
int jjMoveStringLiteralDfa4_0 (long old0, long active0)
int jjMoveStringLiteralDfa5_0 (long old0, long active0)
int jjMoveStringLiteralDfa6_0 (long old0, long active0)
int jjStartNfaWithStates_0 (int pos, int kind, int state)
int jjMoveNfa_0 (int startState, int curPos)
void ReInitRounds ()
void jjCheckNAdd (int state)
void jjAddStates (int start, int end)
void jjCheckNAddTwoStates (int state1, int state2)
void jjCheckNAddStates (int start, int end)
Static Private Attributes
static final int[] jjrounds = new int[187]
static final int[] jjstateSet = new int[374]
Detailed Description
Token Manager.
Definition at line 7 of file LogoParserTokenManager.java.
Constructor & Destructor Documentation
parser.LogoParserTokenManager.LogoParserTokenManager (SimpleCharStream stream)
Constructor.
Definition at line 1369 of file LogoParserTokenManager.java.
References parser.SimpleCharStream.staticFlag.
parser.LogoParserTokenManager.LogoParserTokenManager (SimpleCharStream stream, int lexState)
Constructor.
Definition at line 1376 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.SwitchTo().
Member Function Documentation
Token parser.LogoParserTokenManager.getNextToken ()
Get the next Token.
Definition at line 1445 of file LogoParserTokenManager.java.
References parser.SimpleCharStream.backup(), parser.SimpleCharStream.BeginToken(), parser.SimpleCharStream.getEndColumn(), parser.SimpleCharStream.getEndLine(), parser.SimpleCharStream.GetImage(), parser.LogoParserTokenManager.jjFillToken(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0(), parser.TokenMgrError.LEXICAL_ERROR, and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParser.getNextToken(), parser.LogoParser.getToken(), parser.LogoParser.jj_consume_token(), and parser.LogoParser.jj_ntk().
void parser.LogoParserTokenManager.jjAddStates (int start, int end) private
Definition at line 1517 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0().
void parser.LogoParserTokenManager.jjCheckNAdd (int state) private
Definition at line 1509 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjround.
Referenced by parser.LogoParserTokenManager.jjCheckNAddStates(), parser.LogoParserTokenManager.jjCheckNAddTwoStates(), and parser.LogoParserTokenManager.jjMoveNfa_0().
void parser.LogoParserTokenManager.jjCheckNAddStates (int start, int end) private
Definition at line 1529 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjCheckNAdd().
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0().
void parser.LogoParserTokenManager.jjCheckNAddTwoStates (int state1, int state2) private
Definition at line 1523 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjCheckNAdd().
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0().
Token parser.LogoParserTokenManager.jjFillToken () protected
Definition at line 1413 of file LogoParserTokenManager.java.
References parser.Token.beginColumn, parser.Token.beginLine, parser.Token.endColumn, parser.Token.endLine, parser.SimpleCharStream.getBeginColumn(), parser.SimpleCharStream.getBeginLine(), parser.SimpleCharStream.getEndColumn(), parser.SimpleCharStream.getEndLine(), parser.SimpleCharStream.GetImage(), parser.LogoParserTokenManager.jjmatchedKind, and parser.Token.newToken().
Referenced by parser.LogoParserTokenManager.getNextToken().
int parser.LogoParserTokenManager.jjMoveNfa_0 (int startState, int curPos) private
Definition at line 369 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjAddStates(), parser.LogoParserTokenManager.jjCheckNAdd(), parser.LogoParserTokenManager.jjCheckNAddStates(), parser.LogoParserTokenManager.jjCheckNAddTwoStates(), parser.LogoParserTokenManager.jjmatchedKind, parser.LogoParserTokenManager.jjmatchedPos, parser.LogoParserTokenManager.jjnewStateCnt, parser.LogoParserTokenManager.jjround, parser.LogoParserTokenManager.jjstateSet, parser.SimpleCharStream.readChar(), and parser.LogoParserTokenManager.ReInitRounds().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0(), parser.LogoParserTokenManager.jjStartNfa_0(), and parser.LogoParserTokenManager.jjStartNfaWithStates_0().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0 () private
Definition at line 136 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.jjmatchedKind, parser.LogoParserTokenManager.jjMoveNfa_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), and parser.LogoParserTokenManager.jjStopAtPos().
Referenced by parser.LogoParserTokenManager.getNextToken().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0 (long active0) private
Definition at line 173 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjmatchedKind, parser.LogoParserTokenManager.jjmatchedPos, parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjStartNfa_0(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0 (long old0, long active0) private
Definition at line 213 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjStartNfa_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopAtPos(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0 (long old0, long active0) private
Definition at line 255 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjStartNfa_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0 (long old0, long active0) private
Definition at line 283 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), parser.LogoParserTokenManager.jjStartNfa_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0 (long old0, long active0) private
Definition at line 315 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0(), parser.LogoParserTokenManager.jjStartNfa_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0().
int parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0 (long old0, long active0) private
Definition at line 341 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjStartNfa_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0().
final int parser.LogoParserTokenManager.jjStartNfa_0 (int pos, long active0) private
Definition at line 126 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjMoveNfa_0(), and parser.LogoParserTokenManager.jjStopStringLiteralDfa_0().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), and parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0().
int parser.LogoParserTokenManager.jjStartNfaWithStates_0 (int pos, int kind, int state) private
Definition at line 361 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curChar, parser.LogoParserTokenManager.input_stream, parser.LogoParserTokenManager.jjmatchedKind, parser.LogoParserTokenManager.jjmatchedPos, parser.LogoParserTokenManager.jjMoveNfa_0(), and parser.SimpleCharStream.readChar().
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), and parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0().
int parser.LogoParserTokenManager.jjStopAtPos (int pos, int kind) private
Definition at line 130 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjmatchedKind, and parser.LogoParserTokenManager.jjmatchedPos.
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0(), and parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0().
final int parser.LogoParserTokenManager.jjStopStringLiteralDfa_0 (int pos, long active0) private
Definition at line 14 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjmatchedKind, and parser.LogoParserTokenManager.jjmatchedPos.
Referenced by parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0(), and parser.LogoParserTokenManager.jjStartNfa_0().
void parser.LogoParserTokenManager.ReInit (SimpleCharStream stream)
Reinitialise parser.
Definition at line 1382 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curLexState, parser.LogoParserTokenManager.defaultLexState, parser.LogoParserTokenManager.jjmatchedPos, parser.LogoParserTokenManager.jjnewStateCnt, and parser.LogoParserTokenManager.ReInitRounds().
Referenced by parser.LogoParser.ReInit(), and parser.LogoParserTokenManager.ReInit().
void parser.LogoParserTokenManager.ReInit (SimpleCharStream stream, int lexState)
Reinitialise parser.
Definition at line 1398 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.ReInit(), and parser.LogoParserTokenManager.SwitchTo().
void parser.LogoParserTokenManager.ReInitRounds () private
Definition at line 1389 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.jjround.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0(), and parser.LogoParserTokenManager.ReInit().
void parser.LogoParserTokenManager.setDebugStream (java.io.PrintStream ds)
Set debug output.
Definition at line 13 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.debugStream.
void parser.LogoParserTokenManager.SwitchTo (int lexState)
Switch to specified lex state.
Definition at line 1405 of file LogoParserTokenManager.java.
References parser.LogoParserTokenManager.curLexState, and parser.TokenMgrError.INVALID_LEXICAL_STATE.
Referenced by parser.LogoParserTokenManager.LogoParserTokenManager(), and parser.LogoParserTokenManager.ReInit().
Member Data Documentation
char parser.LogoParserTokenManager.curChar static protected
Definition at line 1367 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0(), and parser.LogoParserTokenManager.jjStartNfaWithStates_0().
int parser.LogoParserTokenManager.curLexState = 0 package
Definition at line 1437 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.ReInit(), and parser.LogoParserTokenManager.SwitchTo().
java.io.PrintStream parser.LogoParserTokenManager.debugStream = System.out
Debug output.
Definition at line 11 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.setDebugStream().
int parser.LogoParserTokenManager.defaultLexState = 0 package
Definition at line 1438 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.ReInit().
SimpleCharStream parser.LogoParserTokenManager.input_stream static protected
Definition at line 1364 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa2_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa3_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa4_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa5_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa6_0(), and parser.LogoParserTokenManager.jjStartNfaWithStates_0().
int parser.LogoParserTokenManager.jjmatchedKind package
Definition at line 1442 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjFillToken(), parser.LogoParserTokenManager.jjMoveNfa_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa0_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopAtPos(), and parser.LogoParserTokenManager.jjStopStringLiteralDfa_0().
int parser.LogoParserTokenManager.jjmatchedPos package
Definition at line 1441 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0(), parser.LogoParserTokenManager.jjMoveStringLiteralDfa1_0(), parser.LogoParserTokenManager.jjStartNfaWithStates_0(), parser.LogoParserTokenManager.jjStopAtPos(), parser.LogoParserTokenManager.jjStopStringLiteralDfa_0(), and parser.LogoParserTokenManager.ReInit().
int parser.LogoParserTokenManager.jjnewStateCnt package
Definition at line 1439 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0(), and parser.LogoParserTokenManager.ReInit().
final int [] parser.LogoParserTokenManager.jjnextStates static package
Initial value:
= {
   171, 173, 175, 177, 179, 186, 148, 152, 153, 159, 165, 169, 96, 105, 109, 119,
   128, 131, 140, 144, 146, 83, 93, 63, 65, 72, 46, 56, 35, 44,
}
Definition at line 1340 of file LogoParserTokenManager.java.
int parser.LogoParserTokenManager.jjround package
Definition at line 1440 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjCheckNAdd(), parser.LogoParserTokenManager.jjMoveNfa_0(), and parser.LogoParserTokenManager.ReInitRounds().
final int [] parser.LogoParserTokenManager.jjrounds = new int[187] static private
Definition at line 1365 of file LogoParserTokenManager.java.
final int [] parser.LogoParserTokenManager.jjstateSet = new int[374] static private
Definition at line 1366 of file LogoParserTokenManager.java.
Referenced by parser.LogoParserTokenManager.jjMoveNfa_0().
final String [] parser.LogoParserTokenManager.jjstrLiteralImages static
Initial value:
= {
"", null, null, null, null, "\162\145\160\145\141\164",
"\165\156\164\151\154", "\167\150\151\154\145", "\151\146", "\151\146\145\154\163\145",
"\154\141\142\145\154", "\155\141\153\145", "\164\157", "\145\156\144", null, null, null, null, null,
null, null, null, null, "\150\157\155\145", null, null,
"\164\157\167\141\162\144\163", null, null, null, null, null, null, null, null, null, "\40\76\75",
"\40\74\75", null, null, "\72", "\133", "\135", }
Token literal values.
Definition at line 1346 of file LogoParserTokenManager.java.
final long [] parser.LogoParserTokenManager.jjtoSkip static package
Initial value:
= {
   0xeL,
}
Definition at line 1361 of file LogoParserTokenManager.java.
final long [] parser.LogoParserTokenManager.jjtoToken static package
Initial value:
= {
   0x7fffffffff1L,
}
Definition at line 1358 of file LogoParserTokenManager.java.
final String [] parser.LogoParserTokenManager.lexStateNames static
Initial value:
= {
   "DEFAULT",
}
Lexer state names.
Definition at line 1355 of file LogoParserTokenManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/parser/LogoParserTokenManager.java