slogo_team12: MovementAndImageAPI.src.TurtleHandler Class Reference
MovementAndImageAPI.src.TurtleHandler Class Reference
Public Member Functions
TurtleHandler (ImageUpdater imageUpdater)
double getOrientation ()
Point2D getTurtleLocation ()
void updateTurtleLocation (double translocation)
void updateTurtleAbsoluteLocation (Point2D newLocation)
void updateTurtleOrientation (double rotation)
void updateTurtleAbsoluteOrientation (double newAngle)
void showTurtle (int show)
void updateImage (Image newImage)
void clearLines ()
void setPenPosition (int penPosition)
int getPenPosition ()
int getShowing ()
PenHandler getPenHandler ()
void setLineWidth (double width)
int getID ()
void towards (Point2D location)
Public Member Functions inherited from MovementAndImageAPI.src.GeneralTurtleHandler
abstract double getOrientation ()
abstract Point2D getTurtleLocation ()
abstract void updateTurtleLocation (double translocation)
abstract void updateTurtleAbsoluteLocation (Point2D newLocation)
abstract void updateTurtleOrientation (double rotation)
abstract void updateTurtleAbsoluteOrientation (double newAngle)
abstract void showTurtle (int show)
abstract void updateImage (Image newImage)
abstract void clearLines ()
abstract void setPenPosition (int penPosition)
abstract int getPenPosition ()
abstract int getShowing ()
abstract PenHandler getPenHandler ()
abstract void setLineWidth (double width)
abstract void towards (Point2D location)
Private Member Functions
Point2D getTurtleLocationInCanvas ()
void moveAndDraw (Point2D from, Point2D to)
Private Attributes
Turtle mainTurtle = new Turtle()
ImageUpdater mainImageUpdater
int myID
Static Private Attributes
static int turtleID = 1
static double RADIAL_CONVERT = 180 / Math.PI
Detailed Description
Author
Eirika Sawh This class handles the actual position of the Turtle, but not updating the image.
Definition at line 11 of file TurtleHandler.java.
Constructor & Destructor Documentation
MovementAndImageAPI.src.TurtleHandler.TurtleHandler (ImageUpdater imageUpdater)
Definition at line 19 of file TurtleHandler.java.
References MovementAndImageAPI.src.TurtleHandler.turtleID.
Member Function Documentation
void MovementAndImageAPI.src.TurtleHandler.clearLines ()
Definition at line 97 of file TurtleHandler.java.
References MovementAndImageAPI.src.ImageUpdater.clearLines().
int MovementAndImageAPI.src.TurtleHandler.getID ()
Returns
the ID associated with this turtle. Making a new TurtleHandler increments the static ID counter by 1.
Definition at line 128 of file TurtleHandler.java.
References MovementAndImageAPI.src.TurtleHandler.myID.
Referenced by MovementAndImageAPI.src.TurtleGroup.addNewTurtle().
double MovementAndImageAPI.src.TurtleHandler.getOrientation ()
Definition at line 25 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getOrientation().
Referenced by TurtleDataFeature.showStage().
PenHandler MovementAndImageAPI.src.TurtleHandler.getPenHandler ()
Definition at line 115 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPenHandler().
Referenced by Workspace.createWorkspace().
int MovementAndImageAPI.src.TurtleHandler.getPenPosition ()
Definition at line 105 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPenPosition().
int MovementAndImageAPI.src.TurtleHandler.getShowing ()
Definition at line 109 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getImage().
Point2D MovementAndImageAPI.src.TurtleHandler.getTurtleLocation ()
Definition at line 29 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPoint().
Referenced by TurtleDataFeature.showStage().
Point2D MovementAndImageAPI.src.TurtleHandler.getTurtleLocationInCanvas () private
Returns
the Point2D where the Turtle would be in the canvas, as opposed to its actual location (although the two might be the same).
Definition at line 38 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPoint(), and MovementAndImageAPI.src.ImageUpdater.getTurtleCanvasSize().
Referenced by MovementAndImageAPI.src.TurtleHandler.towards().
void MovementAndImageAPI.src.TurtleHandler.moveAndDraw (Point2D from, Point2D to) private
Parameters
from The start point of the line
to The end point of the line, also where the Turtle image should be moved to
Definition at line 67 of file TurtleHandler.java.
References MovementAndImageAPI.src.ImageUpdater.drawLine(), MovementAndImageAPI.src.Turtle.getImage(), MovementAndImageAPI.src.Turtle.getPenHandler(), MovementAndImageAPI.src.Turtle.getPenPosition(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
Referenced by MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteLocation(), and MovementAndImageAPI.src.TurtleHandler.updateTurtleLocation().
void MovementAndImageAPI.src.TurtleHandler.setLineWidth (double width)
Definition at line 119 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPenHandler(), and MovementAndImageAPI.src.PenHandler.setLineWidth().
void MovementAndImageAPI.src.TurtleHandler.setPenPosition (int penPosition)
Definition at line 101 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.setPenPosition().
void MovementAndImageAPI.src.TurtleHandler.showTurtle (int show)
Definition at line 85 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getImage(), MovementAndImageAPI.src.Turtle.getPoint(), MovementAndImageAPI.src.Turtle.show(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
void MovementAndImageAPI.src.TurtleHandler.towards (Point2D location)
Definition at line 132 of file TurtleHandler.java.
References MovementAndImageAPI.src.TurtleHandler.getTurtleLocationInCanvas(), MovementAndImageAPI.src.TurtleHandler.RADIAL_CONVERT, and MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteOrientation().
void MovementAndImageAPI.src.TurtleHandler.updateImage (Image newImage)
Definition at line 91 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getImage(), MovementAndImageAPI.src.Turtle.getPoint(), MovementAndImageAPI.src.Turtle.updateImage(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
Referenced by Workspace.createWorkspace(), and TurtleChooserFeature.openTurtleChooser().
void MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteLocation (Point2D newLocation)
Definition at line 52 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPoint(), MovementAndImageAPI.src.TurtleHandler.moveAndDraw(), and MovementAndImageAPI.src.Turtle.updateAbsoluteLocation().
void MovementAndImageAPI.src.TurtleHandler.updateTurtleAbsoluteOrientation (double newAngle)
Definition at line 79 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getImage(), MovementAndImageAPI.src.Turtle.getPoint(), MovementAndImageAPI.src.Turtle.updateAbsoluteOrientation(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
Referenced by MovementAndImageAPI.src.TurtleHandler.towards().
void MovementAndImageAPI.src.TurtleHandler.updateTurtleLocation (double translocation)
Definition at line 45 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getPoint(), MovementAndImageAPI.src.TurtleHandler.moveAndDraw(), and MovementAndImageAPI.src.Turtle.updateLocation().
Referenced by Main.addKeyboardControl().
void MovementAndImageAPI.src.TurtleHandler.updateTurtleOrientation (double rotation)
Definition at line 73 of file TurtleHandler.java.
References MovementAndImageAPI.src.Turtle.getImage(), MovementAndImageAPI.src.Turtle.getPoint(), MovementAndImageAPI.src.Turtle.updateOrientation(), and MovementAndImageAPI.src.ImageUpdater.updateTurtleImage().
Referenced by Main.addKeyboardControl().
Member Data Documentation
ImageUpdater MovementAndImageAPI.src.TurtleHandler.mainImageUpdater private
Definition at line 14 of file TurtleHandler.java.
Turtle MovementAndImageAPI.src.TurtleHandler.mainTurtle = new Turtle() private
Definition at line 13 of file TurtleHandler.java.
int MovementAndImageAPI.src.TurtleHandler.myID private
Definition at line 16 of file TurtleHandler.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.getID().
double MovementAndImageAPI.src.TurtleHandler.RADIAL_CONVERT = 180 / Math.PI static private
Definition at line 17 of file TurtleHandler.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.towards().
int MovementAndImageAPI.src.TurtleHandler.turtleID = 1 static private
Definition at line 15 of file TurtleHandler.java.
Referenced by MovementAndImageAPI.src.TurtleHandler.TurtleHandler().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/MovementAndImageAPI/src/TurtleHandler.java