slogo_team12: parser.LogoParser Class Reference
parser.LogoParser Class Reference
Public Member Functions
ICommand parse (CommandsFactory factory) throws ParseException
final ICommand expression (CommandsFactory factory) throws ParseException
final ICommand list (CommandsFactory factory) throws ParseException
final ICommand statement (CommandsFactory factory) throws ParseException
final double eval () throws ParseException
final double arithm () throws ParseException
final double term () throws ParseException
final double pow () throws ParseException
LogoParser (java.io.InputStream stream)
LogoParser (java.io.InputStream stream, String encoding)
void ReInit (java.io.InputStream stream)
void ReInit (java.io.InputStream stream, String encoding)
LogoParser (java.io.Reader stream)
void ReInit (java.io.Reader stream)
LogoParser (LogoParserTokenManager tm)
void ReInit (LogoParserTokenManager tm)
final Token getNextToken ()
final Token getToken (int index)
ParseException generateParseException ()
final void enable_tracing ()
final void disable_tracing ()
Public Attributes
LogoParserTokenManager token_source
Token token
Token jj_nt
Public Attributes inherited from parser.LogoParserConstants
int EOF = 0
int EOL = 4
int REPEAT = 5
int UNTIL = 6
int WHILE = 7
int IF = 8
int IFELSE = 9
int LABEL = 10
int MAKE = 11
int TO = 12
int END = 13
int FORWARD = 14
int BACK = 15
int RIGHT = 16
int LEFT = 17
int CLEAR = 18
int PENUP = 19
int PENDOWN = 20
int HIDE = 21
int SHOW = 22
int HOME = 23
int SETXY = 24
int SETHEADING = 25
int TOWARDS = 26
int SETPENSIZE = 27
int NUM = 28
int SUM = 29
int SUB = 30
int MULT = 31
int DIV = 32
int POW = 33
int GT = 34
int LT = 35
int GE = 36
int LE = 37
int EQ = 38
int STRING = 39
int COLON = 40
int LBRACKET = 41
int RBRACKET = 42
int DEFAULT = 0
String[] tokenImage
Static Package Functions
[static initializer]
Package Attributes
SimpleCharStream jj_input_stream
Private Member Functions
Token jj_consume_token (int kind) throws ParseException
int jj_ntk ()
Static Private Member Functions
static void jj_la1_init_0 ()
static void jj_la1_init_1 ()
Private Attributes
int jj_ntk
int jj_gen
final int[] jj_la1 = new int[14]
java.util.List< int[]> jj_expentries = new java.util.ArrayList<int[]>()
int[] jj_expentry
int jj_kind = -1
Static Private Attributes
static int[] jj_la1_0
static int[] jj_la1_1
Detailed Description
Definition at line 6 of file LogoParser.java.
Constructor & Destructor Documentation
parser.LogoParser.LogoParser (java.io.InputStream stream)
Constructor with InputStream.
Definition at line 541 of file LogoParser.java.
parser.LogoParser.LogoParser (java.io.InputStream stream, String encoding)
Constructor with InputStream and supplied encoding
Definition at line 545 of file LogoParser.java.
parser.LogoParser.LogoParser (java.io.Reader stream)
Constructor.
Definition at line 569 of file LogoParser.java.
parser.LogoParser.LogoParser (LogoParserTokenManager tm)
Constructor with generated Token Manager.
Definition at line 589 of file LogoParser.java.
Member Function Documentation
parser.LogoParser.[static initializer] () static package
final double parser.LogoParser.arithm () throws ParseException
Definition at line 415 of file LogoParser.java.
References parser.LogoParser.jj_consume_token(), parser.LogoParser.jj_gen, parser.LogoParser.jj_la1, parser.LogoParser.jj_ntk(), parser.LogoParserConstants.SUB, parser.LogoParserConstants.SUM, and parser.LogoParser.term().
Referenced by parser.LogoParser.eval().
final void parser.LogoParser.disable_tracing ()
Disable tracing.
Definition at line 690 of file LogoParser.java.
final void parser.LogoParser.enable_tracing ()
Enable tracing.
Definition at line 686 of file LogoParser.java.
final double parser.LogoParser.eval () throws ParseException
Definition at line 363 of file LogoParser.java.
References parser.LogoParser.arithm(), parser.LogoParserConstants.EQ, parser.LogoParserConstants.GE, parser.LogoParserConstants.GT, parser.LogoParser.jj_consume_token(), parser.LogoParser.jj_gen, parser.LogoParser.jj_la1, parser.LogoParser.jj_ntk(), parser.LogoParserConstants.LE, and parser.LogoParserConstants.LT.
Referenced by parser.LogoParser.list(), and parser.LogoParser.statement().
final ICommand parser.LogoParser.expression (CommandsFactory factory) throws ParseException
Definition at line 13 of file LogoParser.java.
References parser.LogoParserConstants.EOL, parser.LogoParser.jj_consume_token(), and parser.LogoParser.list().
ParseException parser.LogoParser.generateParseException ()
Generate ParseException.
Definition at line 652 of file LogoParser.java.
References parser.LogoParser.jj_kind, and parser.LogoParserConstants.tokenImage.
Referenced by parser.LogoParser.jj_consume_token().
final Token parser.LogoParser.getNextToken ()
Get the next Token.
Definition at line 622 of file LogoParser.java.
References parser.LogoParserTokenManager.getNextToken(), parser.Token.next, and parser.LogoParser.token.
final Token parser.LogoParser.getToken (int index)
Get the specific Token.
Definition at line 631 of file LogoParser.java.
References parser.LogoParserTokenManager.getNextToken(), parser.Token.next, and parser.LogoParser.token.
Token parser.LogoParser.jj_consume_token (int kind) throws ParseException private
Definition at line 606 of file LogoParser.java.
References parser.LogoParser.generateParseException(), parser.LogoParserTokenManager.getNextToken(), parser.LogoParser.jj_kind, parser.Token.kind, parser.Token.next, and parser.LogoParser.token.
Referenced by parser.LogoParser.arithm(), parser.LogoParser.eval(), parser.LogoParser.expression(), parser.LogoParser.list(), parser.LogoParser.pow(), parser.LogoParser.statement(), and parser.LogoParser.term().
static void parser.LogoParser.jj_la1_init_0 () static private
Definition at line 533 of file LogoParser.java.
static void parser.LogoParser.jj_la1_init_1 () static private
Definition at line 536 of file LogoParser.java.
int parser.LogoParser.jj_ntk () private
Definition at line 640 of file LogoParser.java.
References parser.LogoParserTokenManager.getNextToken(), parser.Token.kind, and parser.Token.next.
Referenced by parser.LogoParser.arithm(), parser.LogoParser.eval(), parser.LogoParser.list(), parser.LogoParser.pow(), parser.LogoParser.statement(), and parser.LogoParser.term().
final ICommand parser.LogoParser.list (CommandsFactory factory) throws ParseException
Definition at line 24 of file LogoParser.java.
References commands.CommandsQueue.addCommand(), parser.LogoParserConstants.BACK, parser.LogoParserConstants.CLEAR, commands.CommandsQueue.CommandsQueue(), parser.LogoParserConstants.END, parser.LogoParser.eval(), parser.LogoParserConstants.FORWARD, parser.LogoParserConstants.HIDE, parser.LogoParserConstants.HOME, parser.LogoParserConstants.IF, parser.LogoParserConstants.IFELSE, parser.LogoParser.jj_consume_token(), parser.LogoParser.jj_gen, parser.LogoParser.jj_la1, parser.LogoParser.jj_ntk(), parser.LogoParserConstants.LBRACKET, parser.LogoParserConstants.LEFT, parser.LogoParserConstants.PENDOWN, parser.LogoParserConstants.PENUP, parser.LogoParserConstants.RBRACKET, parser.LogoParserConstants.REPEAT, parser.LogoParserConstants.RIGHT, parser.LogoParserConstants.SETHEADING, parser.LogoParserConstants.SETPENSIZE, parser.LogoParserConstants.SETXY, parser.LogoParserConstants.SHOW, parser.LogoParser.statement(), parser.LogoParserConstants.STRING, parser.LogoParserConstants.TO, parser.Token.toString(), and parser.LogoParserConstants.TOWARDS.
Referenced by parser.LogoParser.expression(), and parser.LogoParser.parse().
ICommand parser.LogoParser.parse (CommandsFactory factory) throws ParseException
Definition at line 7 of file LogoParser.java.
References parser.LogoParser.list().
Referenced by parser.Parser.parse().
final double parser.LogoParser.pow () throws ParseException
Definition at line 491 of file LogoParser.java.
References parser.LogoParser.jj_consume_token(), parser.LogoParser.jj_gen, parser.LogoParser.jj_la1, parser.LogoParser.jj_ntk(), parser.LogoParserConstants.NUM, parser.LogoParserConstants.POW, and parser.Token.toString().
Referenced by parser.LogoParser.term().
void parser.LogoParser.ReInit (java.io.InputStream stream)
Reinitialise.
Definition at line 555 of file LogoParser.java.
Referenced by parser.Parser.parse().
void parser.LogoParser.ReInit (java.io.InputStream stream, String encoding)
Reinitialise.
Definition at line 559 of file LogoParser.java.
References parser.SimpleCharStream.ReInit(), and parser.LogoParserTokenManager.ReInit().
void parser.LogoParser.ReInit (java.io.Reader stream)
Reinitialise.
Definition at line 579 of file LogoParser.java.
References parser.SimpleCharStream.ReInit(), and parser.LogoParserTokenManager.ReInit().
void parser.LogoParser.ReInit (LogoParserTokenManager tm)
Reinitialise.
Definition at line 598 of file LogoParser.java.
final ICommand parser.LogoParser.statement (CommandsFactory factory) throws ParseException
Definition at line 284 of file LogoParser.java.
References parser.LogoParserConstants.BACK, parser.LogoParserConstants.CLEAR, parser.LogoParser.eval(), parser.LogoParserConstants.FORWARD, parser.LogoParserConstants.HIDE, parser.LogoParserConstants.HOME, parser.LogoParser.jj_consume_token(), parser.LogoParser.jj_gen, parser.LogoParser.jj_la1, parser.LogoParser.jj_ntk(), parser.LogoParserConstants.LEFT, parser.LogoParserConstants.PENDOWN, parser.LogoParserConstants.PENUP, parser.LogoParserConstants.RIGHT, parser.LogoParserConstants.SETHEADING, parser.LogoParserConstants.SETPENSIZE, parser.LogoParserConstants.SETXY, parser.LogoParserConstants.SHOW, and parser.LogoParserConstants.TOWARDS.
Referenced by parser.LogoParser.list().
final double parser.LogoParser.term () throws ParseException
Definition at line 453 of file LogoParser.java.
References parser.LogoParserConstants.DIV, parser.LogoParser.jj_consume_token(), parser.LogoParser.jj_gen, parser.LogoParser.jj_la1, parser.LogoParser.jj_ntk(), parser.LogoParserConstants.MULT, and parser.LogoParser.pow().
Referenced by parser.LogoParser.arithm().
Member Data Documentation
java.util.List<int[]> parser.LogoParser.jj_expentries = new java.util.ArrayList<int[]>() private
Definition at line 647 of file LogoParser.java.
int [] parser.LogoParser.jj_expentry private
Definition at line 648 of file LogoParser.java.
int parser.LogoParser.jj_gen private
Definition at line 525 of file LogoParser.java.
Referenced by parser.LogoParser.arithm(), parser.LogoParser.eval(), parser.LogoParser.list(), parser.LogoParser.pow(), parser.LogoParser.statement(), and parser.LogoParser.term().
SimpleCharStream parser.LogoParser.jj_input_stream package
Definition at line 519 of file LogoParser.java.
int parser.LogoParser.jj_kind = -1 private
Definition at line 649 of file LogoParser.java.
Referenced by parser.LogoParser.generateParseException(), and parser.LogoParser.jj_consume_token().
final int [] parser.LogoParser.jj_la1 = new int[14] private
Definition at line 526 of file LogoParser.java.
Referenced by parser.LogoParser.arithm(), parser.LogoParser.eval(), parser.LogoParser.list(), parser.LogoParser.pow(), parser.LogoParser.statement(), and parser.LogoParser.term().
int [] parser.LogoParser.jj_la1_0 static private
Definition at line 527 of file LogoParser.java.
int [] parser.LogoParser.jj_la1_1 static private
Definition at line 528 of file LogoParser.java.
Token parser.LogoParser.jj_nt
Next token.
Definition at line 523 of file LogoParser.java.
int parser.LogoParser.jj_ntk private
Definition at line 524 of file LogoParser.java.
Token parser.LogoParser.token
Current token.
Definition at line 521 of file LogoParser.java.
Referenced by parser.LogoParser.getNextToken(), parser.LogoParser.getToken(), and parser.LogoParser.jj_consume_token().
LogoParserTokenManager parser.LogoParser.token_source
Generated Token Manager.
Definition at line 518 of file LogoParser.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/parser/LogoParser.java