slogo_team12: parser.Parser Class Reference
parser.Parser Class Reference
Public Member Functions
Parser (CommandsFactory commandsFactory)
void setForeignLanguage (String language)
void createLogoParser ()
ICommand parseFile (File input) throws Exception
ICommand parse (String input) throws Exception
Static Package Functions
static String readFile (String path, Charset encoding) throws IOException
Private Member Functions
String translateInput (String input)
String buildSpaceSeparatedString (String[] splitString)
Private Attributes
CommandsFactory commandsFactory = null
LogoParser myLogoParser
Static Private Attributes
static ResourceBundle ourLanguageBundle
static final String RESOURCELOCATION = "resources.languages"
static final String DOT = "."
Detailed Description
Main parser class called by the front-end Able to take a file or string and translate it if needed, then send it to the logoParser class
Author
Davis
Definition at line 24 of file Parser.java.
Constructor & Destructor Documentation
parser.Parser.Parser (CommandsFactory commandsFactory)
Definition at line 33 of file Parser.java.
References parser.Parser.commandsFactory.
Member Function Documentation
String parser.Parser.buildSpaceSeparatedString (String[] splitString) private
helper method to turn an array of strings into a space-seperated string
Parameters
splitString string array
Returns
joined string
Definition at line 118 of file Parser.java.
Referenced by parser.Parser.translateInput().
void parser.Parser.createLogoParser ()
Definition at line 52 of file Parser.java.
Referenced by Workspace.createWorkspace(), and input.InputExecutor.InputExecutor().
ICommand parser.Parser.parse (String input) throws Exception
parse an input string by sending it to the logoParser
Parameters
input string to parse
Definition at line 71 of file Parser.java.
References parser.LogoParser.parse(), parser.LogoParser.ReInit(), and parser.Parser.translateInput().
Referenced by parser.Parser.parseFile(), input.InputExecutor.processInput(), and Workspace.sendUserInput().
ICommand parser.Parser.parseFile (File input) throws Exception
parse a file by converting it to a string and parsing it as such
Parameters
input file to parse
Definition at line 61 of file Parser.java.
References parser.Parser.parse(), and parser.Parser.readFile().
Referenced by FileChooserFeature.openFileChooser().
static String parser.Parser.readFile (String path, Charset encoding) throws IOException static package
helper method for turning a file into a string
Parameters
path file path
encoding character encoding
Definition at line 136 of file Parser.java.
Referenced by parser.Parser.parseFile().
void parser.Parser.setForeignLanguage (String language)
set parser to translate a file from another language to english
Parameters
language language string of a matching resource bundle
Definition at line 42 of file Parser.java.
Referenced by Workspace.addFeatureButtons().
String parser.Parser.translateInput (String input) private
translate a given input by looking at words and checking for matches in the resource bundle
Parameters
input string to translate
Definition at line 88 of file Parser.java.
References parser.Parser.buildSpaceSeparatedString().
Referenced by parser.Parser.parse().
Member Data Documentation
CommandsFactory parser.Parser.commandsFactory = null private
Definition at line 29 of file Parser.java.
Referenced by parser.Parser.Parser().
final String parser.Parser.DOT = "." static private
Definition at line 28 of file Parser.java.
LogoParser parser.Parser.myLogoParser private
Definition at line 30 of file Parser.java.
ResourceBundle parser.Parser.ourLanguageBundle static private
Definition at line 26 of file Parser.java.
final String parser.Parser.RESOURCELOCATION = "resources.languages" static private
Definition at line 27 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/parser/Parser.java