slogo_team12: Workspace Class Reference
Workspace Class Reference
Public Member Functions
TurtleHandler getTurtleHandler ()
Tab createWorkspace (Stage primaryStage, Group root)
Node addFeatureButtons (BorderPane bpane, Stage primaryStage, Pane pane, PenHandler penHandler, TurtleHandler turtleHandler, Group root, ImageUpdater iu)
void sendUserInput (TextField textBox, ListView< Text > prevCommandListView)
void setUpPreviousCommands (ListView< Text > prevCommandListView)
Private Attributes
Canvas myBackDisplay
Canvas myLineCanvas
Canvas myTurtleCanvas
CommandsFactory commandsFactory
Parser parser
GraphicsContext gcBack
TurtleHandler myTurtleHandler
ArrayList< Text > prevCommandList
ObservableList< Text > prevCommandObsvList
Map< Text, ICommand > prevCommandMap
String userInput
Button RefGridButton
Button HelpPageButton
Button TCButton
Button TurtleDataButton
Button FileChooserButton
Static Private Attributes
static final int DISPLAY_WIDTH = 700
static final int DISPLAY_HEIGHT = 600
Detailed Description
Sets up the Slogo workspace which contains the feature buttons, display, previous commands list, and user input area.
Author
Yoonhyung Choi
Definition at line 40 of file Workspace.java.
Member Function Documentation
Node Workspace.addFeatureButtons (BorderPane bpane, Stage primaryStage, Pane pane, PenHandler penHandler, TurtleHandler turtleHandler, Group root, ImageUpdater iu)
Adds features and associated buttons.
Definition at line 142 of file Workspace.java.
References ColorFeature.changeBGColor(), ColorFeature.changePenColor(), Feature.Feature.makeButton(), FileChooserFeature.openFileChooser(), HelpPageFeature.openHelpPage(), TurtleChooserFeature.openTurtleChooser(), TurtleDataFeature.openTurtleDataPage(), parser.Parser.setForeignLanguage(), and RefGridFeature.showReferenceGrid().
Referenced by createWorkspace().
Tab Workspace.createWorkspace (Stage primaryStage, Group root)
Creates the Slogo workspace
Parameters
primaryStage Stage where the workspace is located
root Group where the workspace is located
Returns
Tab that contains the workspace
Definition at line 75 of file Workspace.java.
References addFeatureButtons(), parser.Parser.createLogoParser(), MovementAndImageAPI.src.TurtleHandler.getPenHandler(), myTurtleHandler, sendUserInput(), commands.CommandsFactory.setTurtleHandler(), and MovementAndImageAPI.src.TurtleHandler.updateImage().
Referenced by Main.start().
TurtleHandler Workspace.getTurtleHandler ()
Returns the turtleHandler in the workspace
Returns
Definition at line 65 of file Workspace.java.
References myTurtleHandler.
Referenced by Main.start().
void Workspace.sendUserInput (TextField textBox, ListView< Text > prevCommandListView)
Sends the user input to the parse, which then executes the command. Adds the command to the previous command list.
Parameters
textBox TextField where the user will enter the command
prevCommandListView ListView for the previous commands
Definition at line 209 of file Workspace.java.
References commands.ICommand.execute(), parser.Parser.parse(), and setUpPreviousCommands().
Referenced by createWorkspace().
void Workspace.setUpPreviousCommands (ListView< Text > prevCommandListView)
Displays a listview of clickable previous commands. Command executes when clicked.
Parameters
prevCommandListView Listview for the previous commands
Definition at line 238 of file Workspace.java.
References commands.ICommand.execute().
Referenced by sendUserInput().
Member Data Documentation
CommandsFactory Workspace.commandsFactory private
Definition at line 47 of file Workspace.java.
final int Workspace.DISPLAY_HEIGHT = 600 static private
Definition at line 43 of file Workspace.java.
final int Workspace.DISPLAY_WIDTH = 700 static private
Definition at line 42 of file Workspace.java.
Button Workspace.FileChooserButton private
Definition at line 59 of file Workspace.java.
GraphicsContext Workspace.gcBack private
Definition at line 49 of file Workspace.java.
Button Workspace.HelpPageButton private
Definition at line 56 of file Workspace.java.
Canvas Workspace.myBackDisplay private
Definition at line 44 of file Workspace.java.
Canvas Workspace.myLineCanvas private
Definition at line 45 of file Workspace.java.
Canvas Workspace.myTurtleCanvas private
Definition at line 46 of file Workspace.java.
TurtleHandler Workspace.myTurtleHandler private
Definition at line 50 of file Workspace.java.
Referenced by createWorkspace(), and getTurtleHandler().
Parser Workspace.parser private
Definition at line 48 of file Workspace.java.
ArrayList<Text> Workspace.prevCommandList private
Definition at line 51 of file Workspace.java.
Map<Text, ICommand> Workspace.prevCommandMap private
Definition at line 53 of file Workspace.java.
ObservableList<Text> Workspace.prevCommandObsvList private
Definition at line 52 of file Workspace.java.
Button Workspace.RefGridButton private
Definition at line 55 of file Workspace.java.
Button Workspace.TCButton private
Definition at line 57 of file Workspace.java.
Button Workspace.TurtleDataButton private
Definition at line 58 of file Workspace.java.
String Workspace.userInput private
Definition at line 54 of file Workspace.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team12/repository/src/Workspace.java